// Define throwable trash items
export const throwableTrashItems = [
    "bottle",
    "cup",
    "can",
    "plastic bag",
    "paper",
    "banana",
    "apple",
    "fork",
    "knife",
    "book",
    "pen",
    "bag",
    "plate",
    "straw",
    "napkin",
    "spoon",
    "newspaper",
    "magazine",
    "cardboard",
    "tissue",
    "wrapping paper",
    "food container",
    "chip bag",
    "plastic wrapper",
    "milk carton",
    "glass bottle",
    "aluminum foil",
    "egg carton",
    "cigarette butt",
    "snack wrapper",
    "juice box",
    "pizza box",
    "toothpick",
    "soda can",
    "yogurt cup",
    "receipt",
    "styrofoam cup",
    "plastic straw",
    "fast food bag",
    "fruit peel",
    "plastic spoon",
    "plastic fork",
    "disposable chopsticks",
    "coffee cup lid",
    "gum wrapper",
    "ice cream stick",
    "disposable gloves",
    "paper bag",
    "glass jar",
    "plastic cap",
    "paper plate",
    "tin can",
    "matchstick",
    "rubber band",
    "broken pen",
    "water bottle cap",
    "candy wrapper",
    "face mask",
    "plastic ring",
    "toothpaste tube",
    "shampoo bottle",
    "conditioner bottle",
    "soap wrapper",
    "pencil shavings",
    "plastic toy",
    "bubble wrap",
    "broken sunglasses",
    "small cardboard box",
    "beer can",
    "energy drink can",
    "sugar packet",
    "plastic fork wrapper",
    "paper cup sleeve",
    "dry tissue",
    "wet wipes",
  ];
  